# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig', models.CharField(max_length=200, verbose_name='phone # of caller')),
                ('dest', models.CharField(max_length=200, verbose_name='phone # to be called')),
                ('timestamp', models.DateTimeField(verbose_name='time of call')),
            ],
        ),
    ]
