# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_caller', '0002_auto_20170601_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliocall',
            name='call_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twiliocall',
            name='call_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twiliocall',
            name='twilio_recording_sid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twiliocall',
            name='twilio_recording_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twiliocall',
            name='twilio_sid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
