# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_caller', '0003_auto_20170601_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliocall',
            name='state',
            field=models.CharField(choices=[('NI', 'Not Initiated'), ('CP', 'Call in Progress'), ('CF', 'Call Finished'), ('TP', 'Transcription in Progress'), ('TC', 'Transcription Complete')], default='NI', max_length=2),
        ),
    ]
