# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_caller', '0004_twiliocall_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliocall',
            name='audio_index_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twiliocall',
            name='recording_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twiliocall',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
