# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_caller', '0005_auto_20170607_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliocall',
            name='phrases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
