# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_caller', '0006_twiliocall_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliocall',
            name='min_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twiliocall',
            name='phrase_results',
            field=models.TextField(blank=True, null=True),
        ),
    ]
