# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_caller', '0007_auto_20170623_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliocall',
            name='participants',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
