# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_caller', '0008_twiliocall_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliocall',
            name='keyword_state',
            field=models.CharField(choices=[('NI', 'Not Initiated'), ('RU', 'Recording Uploaded'), ('KI', 'Keywords Indexed'), ('MN', 'Manual Notes taken')], default='RU', max_length=2),
        ),
    ]
